name: Pyhton Workflow

on:
    push:
        branches: [ "main" ]
    pull_request:
        branches: [ "main" ]

    workflow_dispatch:

jobs:
    testing:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Install dependencies
              run: python -m pip install --upgrade pip
            - name: Test with Pytest
              run: |
                pip install pytest pytest-cov
                pytest main.py
    linting:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: '3.x'
            - name: Install dependensies
              run: python -m pip install --upgrade pip
            - name: Python Linting
              run: |
                pip install pylint
                pylint main.py